### ISSUE TITLE
[bug] in cluster generation

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#58]
@scottfredericks 
I guess there is a serious bug when you change the source code for cluster generation. 
When I did random clusters with C1 symmetry, here is the distribution of energies after relaxation:
![LJ38-10000samples-hist](https://user-images.githubusercontent.com/29445366/55501635-b00a5780-55ff-11e9-84a7-ba15ef004c5d.png)

Here is the results which I did with the version of commit 4d2415a9ace8e24e1280162ddcb7d0bbdd7f76aa 
![Feb-LJ38-10000samples-hist](https://user-images.githubusercontent.com/29445366/55503240-23619880-5603-11e9-8553-efeeec60185b.png)

Clearly, there are some changes which ruined the code for cluster generation.

**Comment by qzhu2017** [comment]
@scottfredericks pay attention to the following commits
https://github.com/qzhu2017/PyXtal/commits/master/pyxtal/crystal.py
after you switched the structure from coordinates to cart/frac_coords, the problems appreared,
6686056
4f7911a 

I suspect you made some mistakes when you transform between Cartesian and fractional coordinates.

**Comment by scottfredericks** [comment]
@qzhu2017 
That sounds like a reasonable cause. Thank you for finding it; I was suspecting it might have been the change in volume or distance tolerance. I will try to fix it immediately.

**Comment by qzhu2017** [comment]
@scottfredericks 
Thanks, I need to run some calculations immediately. I don't want to run it on the old version of code.

**Comment by scottfredericks** [comment]
@qzhu2017 
The frac_coord / cart_coord issue should be fixed now. I had forgotten that the lattice matrix used for clusters and other structure types is different, and that we use absolute coordinates during the cluster generation algorithm (as opposed to fractional for all others).

I will try to run some more cluster tests myself as well.

**Comment by qzhu2017** [comment]
@scottfredericks  I don't think it has been fixed. Still I got a lot of structures with high energy after optimization. They occur more frequently than the code before Feb. 27.

**Comment by qzhu2017** [comment]
@scottfredericks  to be more specific
Below is the results which I obtained from Feb 26 version
```
  1 2019-04-03 11:13:43,066 :: -------------calculation is complete------------
  2 2019-04-03 12:31:36,037 :: ID:    0 PG initial: C1   relaxed: C1   C1   Energy:  -170.934  -166.092
  3 2019-04-03 12:32:06,016 :: ID:  100 PG initial: C1   relaxed: C1   C*v  Energy:  -163.351  -160.954
  4 2019-04-03 12:32:26,998 :: ID:  200 PG initial: C1   relaxed: C1   C1   Energy:  -168.475  -165.429
  5 2019-04-03 12:33:26,562 :: ID:  400 PG initial: C1   relaxed: C1   C1   Energy:  -169.467  -167.796
  6 2019-04-03 12:34:13,621 :: ID:  500 PG initial: C1   relaxed: C1   C1   Energy:  -167.750  -164.558
  7 2019-04-03 12:35:04,545 :: ID:  300 PG initial: C1   relaxed: C1   C1   Energy:  -167.276  -168.625
  8 2019-04-03 12:36:05,728 :: ID:  600 PG initial: C1   relaxed: C1   C*v  Energy:  -157.720  -161.449
  9 2019-04-03 12:37:12,627 :: ID:  800 PG initial: C1   relaxed: C1   C1   Energy:  -166.788  -166.749
 10 2019-04-03 12:38:08,075 :: ID:  900 PG initial: C1   relaxed: C1   C*v  Energy:  -163.582  -162.671
 11 2019-04-03 12:38:26,570 :: ID:  700 PG initial: C1   relaxed: C1   C1   Energy:  -165.546  -165.967
```
Here I used both CG and BFGS algorithms to perform the relaxation. You can see after relaxation, all energies are close to -160.***

I also used the code after your recent fix:
```
 13 2019-04-03 14:01:52,113 :: ID:    0 PG initial: C1   relaxed: C1   C1   Energy:   -66.127  -162.655
 14 2019-04-03 14:05:47,032 :: ID:    0 PG initial: C1   relaxed: C1   C1   Energy:   -29.111   -56.213
 15 2019-04-03 14:06:24,252 :: ID:    0 PG initial: C1   relaxed: C1   C1   Energy:   -93.209  -162.215
 16 2019-04-03 14:07:06,003 :: ID:  100 PG initial: C1   relaxed: C1   C1   Energy:   -78.251   -98.217
 17 2019-04-03 14:07:58,809 :: ID:  200 PG initial: C1   relaxed: C1   C1   Energy:  -150.365  -166.731
 18 2019-04-03 14:09:10,966 :: ID:  400 PG initial: C1   relaxed: C1   C1   Energy:   -59.025  -166.852
 19 2019-04-03 14:10:15,980 :: ID:  500 PG initial: C1   relaxed: C1   C1   Energy:  -122.248  -137.791
 20 2019-04-03 14:10:47,102 :: ID:  300 PG initial: C1   relaxed: C1   C1   Energy:   -54.942   -72.524
 21 2019-04-03 14:12:50,600 :: ID:  600 PG initial: C1   relaxed: C1   C1   Energy:   -82.060  -159.368
 22 2019-04-03 14:13:43,331 :: ID:  700 PG initial: C1   relaxed: C1   C1   Energy:  -134.058  -165.452
 23 2019-04-03 14:14:08,709 :: ID:  800 PG initial: C1   relaxed: C1   C1   Energy:   -77.816  -159.342
 24 2019-04-03 14:14:58,332 :: ID:  900 PG initial: C1   relaxed: C1   C1   Energy:   -18.143  -165.949
```
Clearly, you can see many structure high pretty high energies after relaxation

**Comment by scottfredericks** [comment]
@qzhu2017 
I will look into the possible causes. It could be from the change in Wyckoff symmetry information. Also, which functions are you using to optimize the structures - is it a particular script?

**Comment by qzhu2017** [comment]
```
qzhu@cms:/scratch/qzhu/github/PyXtal$ python examples/01-compare_optalg.py -d 3 -n 38 -m 10  

Reference for LJ  38 is     -173.928 eV, PG: Oh  

Performing random search at 3D space

ID:    0 PG initial: C1   relaxed: C1   C1   Energy:  -162.520  -157.613
ID:    1 PG initial: C1   relaxed: C1   C1   Energy:   -70.881  -117.723
ID:    2 PG initial: C1   relaxed: C1   C1   Energy:   -26.716   -54.836
ID:    3 PG initial: C1   relaxed: C1   C1   Energy:   -71.478  -158.293
ID:    4 PG initial: C1   relaxed: C1   C1   Energy:  -115.735  -158.687
ID:    5 PG initial: C1   relaxed: C1   C1   Energy:   -75.115  -165.869
ID:    6 PG initial: C1   relaxed: C1   C1   Energy:  -130.032  -163.040
ID:    7 PG initial: C1   relaxed: C1   C1   Energy:   -80.579  -156.129
ID:    8 PG initial: C1   relaxed: C1   C1   Energy:   -85.113  -165.147
ID:    9 PG initial: C1   relaxed: C1   C1   Energy:  -104.048  -154.888
```
```
qzhu@cms:/scratch/qzhu/github/PyXtal$ python examples/01-compare_optalg.py -d 3 -n 38 -m 10

Reference for LJ  38 is     -173.928 eV, PG: Oh  

Performing random search at 3D space

ID:    0 PG initial: C1   relaxed: C1   C1   Energy:  -169.404  -166.260
ID:    1 PG initial: C1   relaxed: C1   C1   Energy:  -168.543  -167.473
ID:    2 PG initial: C1   relaxed: C1   C1   Energy:  -168.674  -164.958
ID:    3 PG initial: C1   relaxed: C1   C*v  Energy:  -167.550  -161.991
ID:    4 PG initial: C1   relaxed: C1   C1   Energy:  -165.149  -162.022
ID:    5 PG initial: C1   relaxed: C1   C*v  Energy:  -164.873  -163.411
ID:    6 PG initial: C1   relaxed: C1   C1   Energy:  -167.553  -166.278
ID:    7 PG initial: C1   relaxed: C1   C*v  Energy:  -163.567  -162.820
ID:    8 PG initial: C1   relaxed: C1   C1   Energy:  -164.795  -161.544
ID:    9 PG initial: C1   relaxed: C1   C1   Energy:  -168.127  -167.667
```
The script is examples/01-compare_optalg.py

**Comment by scottfredericks** [comment]
@qzhu2017 
I am still trying to determine the cause. It is definitely only the differences in crystal.py, but I can't figure out why the cart_coords or frac_coords would be causing an issue. I did try running the new version with Carbon or Hydrogen instead of Molybdenum; this makes me think it might have been an issue with distance checking. I just removed the debug print statement from the current version; sorry, I somehow missed it when running test_all.py

**Comment by qzhu2017** [comment]
@scottfredericks 
I just did a couple of test, it looks like there are two major differences,
1, wrong assignment of cart_coords (now you fixed it)
2, the merge of wyckoffs
I think the following commit also changed the results
https://github.com/qzhu2017/PyXtal/commit/6a06462b88a54d246ef6aec46ffb25f7a58d478e

I applied the fix of cart_coords up to the above commit, then I found the results went wrong.
Please let me know what you think.

**Comment by scottfredericks** [comment]
@qzhu2017 
I've been checking, but I can't figure out how changing the behavior of merge_wyckoff would change anything, since we are only testing the C1 case.

After changing 'Mo' to 'C' on line 132 of 01-compare_optalg.py, it seems that the energies are closer to the ground state. This is because the clusters generated are smaller, since Mo has a larger radius than Carbon. I cannot remember exactly when the cluster distance checking issues were fixed and implemented, but I think there were a few between Feb 26 and the current commit. I think that Molybdenum may have been working at the time because the distance checking was wrong. Please take a look at the results for Carbon or Hydrogen and let me know what you think. I will keep looking in the mean time.

**Comment by qzhu2017** [comment]
When you change from 'Mo' to 'C', the results gets slightly better. But I believe there is a major issue in the code.
Let me explain what I did.
First, use the `git checkout` command to return to the older version.
If I returned to dbe9420
$ git checkout dbe9420
I then edited the file of crystal.py to fix the followings,
```python
2182                                     #coords_toadd = filtered_coords(apply_ops(point, self.group[wp_index]), PBC=self.PBC)
2183                                     coords_toadd = filtered_coords(coords_toadd, PBC=self.PBC)
```
p.s., I still don't know why this matters. But it matters! please check why you couldn't use apply_ops.
```python
2268                         #self.cart_coords = np.dot(final_coor, final_lattice)
2269                         self.cart_coords = np.array(final_coor)
```
Then I reinstall it.

```
qzhu@cms:/scratch/qzhu/github/PyXtal$ python setup.py install
qzhu@cms:/scratch/qzhu/github/PyXtal$ python 01.py -d 3 -n 38 -m 10

Reference for LJ  38 is     -173.928 eV, PG: Oh  

Performing random search at 3D space

ID:    0 PG initial: C1   relaxed: C1   C1   Energy:  -154.150  -153.648
ID:    1 PG initial: C1   relaxed: C1   C1   Energy:  -169.386  -167.146
ID:    2 PG initial: C1   relaxed: C1   C1   Energy:  -166.515  -165.954
ID:    3 PG initial: C1   relaxed: C1   C1   Energy:  -169.409  -167.905
ID:    4 PG initial: C1   relaxed: C1   C*v  Energy:  -153.380  -163.327
ID:    5 PG initial: C1   relaxed: C1   C1   Energy:  -166.455  -166.907
ID:    6 PG initial: C1   relaxed: C1   C1   Energy:  -169.324  -163.097
ID:    7 PG initial: C1   relaxed: C1   C1   Energy:  -166.999  -168.278
ID:    8 PG initial: C1   relaxed: C1   C1   Energy:  -167.742  -167.653
ID:    9 PG initial: C1   relaxed: C1   C1   Energy:  -165.402  -151.394
```
I did the same thing when I dated back to  b8f1a73, but the results went wrong.
```
qzhu@cms:/scratch/qzhu/github/PyXtal$ python 01.py -d 3 -n 38 -m 10

Reference for LJ  38 is     -173.928 eV, PG: Oh  

Performing random search at 3D space

ID:    0 PG initial: C1   relaxed: C1   C1   Energy:   -81.219  -117.018
ID:    1 PG initial: C1   relaxed: C1   C1   Energy:  -125.290  -160.264
ID:    2 PG initial: C1   relaxed: C1   C1   Energy:   -91.376  -133.630
ID:    3 PG initial: C1   relaxed: C1   C1   Energy:   -97.019  -106.522
ID:    4 PG initial: C1   relaxed: C1   C1   Energy:  -121.485  -159.175
ID:    5 PG initial: C1   relaxed: C1   C1   Energy:   -91.107  -157.407
ID:    6 PG initial: C1   relaxed: C1   C1   Energy:  -101.759  -163.538
ID:    7 PG initial: C1   relaxed: C1   C1   Energy:  -150.736  -165.276
ID:    8 PG initial: C1   relaxed: C1   C1   Energy:  -125.857  -163.978
ID:    9 PG initial: C1   relaxed: C1   C1   Energy:   -78.693  -161.950
```
Ideally, you should find the values in the last two column are close to 150-160.

You can use the same approach to check what you did. Please do it asap!

**Comment by scottfredericks** [comment]
@qzhu2017 
For this version of the code (dbe9420), we converted back and forth between fractional and absolute coordinates for clusters. The value stored in point gets changed back and forth as well, so the implementation is incorrect. There are several places where the code needs to work together; I am trying to figure out a solution for this implementation that satisfies everything, and how to change it for our current implementation.

**Comment by scottfredericks** [comment]
@qzhu2017 
I think I understand now. So, in dbe920, for each of the distance checks, we use the cell_matrix for the 0D lattice; that is, a lattice other than the Euclidean lattice. So, unless we want to add conditionals for each distance check, we need to use the fractional value for coords_toadd. If we apply the changes which you mentioned to 2182 and 2183, this will be the case. Then, on lines 2268/2269, we actually do need to multiply by the lattice, since our coordinates up to that point are fractional.

So, I think the effect of replacing line 2268 with 2269, is to decrease the scale of the coordinates, which gives lower energies, but might create small distances. I will run some distance checks on the final output clusters to see if this is the case or not.

**Comment by qzhu2017** [comment]
@scottfredericks , I think you are right, I shouldn't do both fix together. 
In addition to these two fixes, I suspect there may also a problem in commit https://github.com/qzhu2017/PyXtal/commit/552f5272f97138b38f47fc5acb54c0aea12411fb#diff-a52d37a201b2754bbe586606ee750b4b

Where the internal matrix may be messed up for clusters.

**Comment by scottfredericks** [comment]
@qzhu2017 
Testing the inter-atomic distances, it looks like the distances are too small whether we apply the changes you used or not; there was some other factor interfering with distance checks for that commit.

**Comment by scottfredericks** [comment]
@qzhu2017 
I might not have explained the matrix_internal idea too well.

For clusters, the Lattice object has two lattices: 1) the Euclidean lattice, which is stored as cell_matrix and used for distance checking, and 2) the internal matrix, which is used only for generating random points, and for calculating the fractional coords after the cluster has generated successfully.

The commit which you linked is the one where I implemented this.

**Comment by scottfredericks** [comment]
@qzhu2017 
Also, I have committed a small script for checking the inter-atomic distances for clusters. This should help for debugging. Note that currently, the script only tests point group 1, but this can easily be changed.

https://github.com/qzhu2017/PyXtal/blob/master/pyxtal/test_cases/check_cluster_distances.py

**Comment by qzhu2017** [comment]
@scottfredericks I see. perhaps you are right about changing Mo to H can help.
It looks like the reason why we had better results is simply because we did a bad job in distance check. Now when we did better in distance check, the generated structures have larger volumes which may be more difficult to get good energies after optimization. 
But please double check if the distance check function and volume functions are implemented correctly in the code.

**Comment by scottfredericks** [comment]
@qzhu2017 
Okay. I will go through all of the distance-related functions for atomic structures tonight.

**Comment by qzhu2017** [comment]
@scottfredericks 
![LJ38-10000samples-hist](https://user-images.githubusercontent.com/29445366/55528638-6e56cc80-5652-11e9-8683-4124af6b8de4.png)
I still believe there must be something wrong with the code. I attempted to generate the structures with H, but you can find the results is not as good as we had in the past

**Comment by scottfredericks** [comment]
@qzhu2017 
The problem was in symmetry.py; we need to use a spherical lattice for C1, not a cylindrical lattice. The reason that using the fractional coordinates worked was not that the atoms were closer together, but that the cartesian coordinates were less uniformly distributed in real space. Ironically, the "bug" which we were turning on and off earlier allowed me to figure this out. We used a cylindrical lattice in the old version too, we were just accidentally turning it off by re-scaling the coordinates back down, which in turn gave us the lower energies.

This should be fixed now, and I am running tests to confirm this. You were right: if the distance and volume calculations are correct, there should not be much difference in the relaxed configuration based on which atomic species atomic species is being used. It should be the relative atomic positions, and not the absolute positions, that count towards the final bond formation.

Also, it seems likely that changing the parameters for cylindrical clusters would be useful. We should be able to get fairly decent results using the cylindrical model, but as we see, the average results could be worsened. Maybe an ellipsoidal model for point generation would work better.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have added two options, -v and -f, which control the volume factor and distance checking factor respectively. My suspicion is that using a lower value for v and a low value for f (though greater than 0), will give somewhat better results.

Using the value "-f 0" will effectively turn off distance checking; I am running a test of this right now.

**Comment by scottfredericks** [comment]
@qzhu2017 

Just turning off distance checking seems not to be enough to improve the results:

![LJ38-10000samples-hist](https://user-images.githubusercontent.com/16890472/55658574-f5bb5180-57b2-11e9-86a1-f4dfebafd2e6.png)

However, using fractional coordinates (which now just scales the coordinates down) and with distance checking turned off (-f 0) seems to improve things:

![LJ38-1000samples-hist](https://user-images.githubusercontent.com/16890472/55658511-c3a9ef80-57b2-11e9-9104-c255f765957d.png)

There is probably some sweet spot for the volume factor and distance factor.

**Comment by qzhu2017** [comment]
@scottfredericks 

I have updated the script related to the cluster optimization. 
PyXtal/examples/example_02_LJ_cluster.py
The problem should be fixed now.
![image](https://user-images.githubusercontent.com/29445366/56073643-7bfc0880-5d5c-11e9-9d65-97fa61f264a7.png)
